name: lunchbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_local_notifications: ^18.0.1
  flutter_stripe: ^11.4.0
  geolocator: ^13.0.2
  go_router: ^14.8.1
  http: ^1.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.1
  share_plus: ^10.1.4
  sqflite: ^2.4.1
  stream_video: ^0.6.0
  stream_video_flutter: ^0.6.0
  stream_video_push_notification: ^0.6.0
  stream_video_screen_sharing: ^0.6.0
  url_launcher: ^6.3.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/google_icon.png
  uses-material-design: true
